name: Deploy Preview

on:
  pull_request:
    branches: [ main ]

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build project
      run: npm run build
    
    - name: Setup Firebase CLI
      run: npm install -g firebase-tools
    
    - name: Deploy to Firebase Preview
      run: firebase hosting:channel:deploy preview-${{ github.event.number }} --expires 7d --token "${{ secrets.FIREBASE_TOKEN }}"
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
    
    - name: Comment PR with preview URL
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `🔍 **Preview deployed!**
            
            Preview URL: https://j-and-j-f8f66--preview-${{ github.event.number }}-zk8xmj4x.web.app
            
            This preview will expire in 7 days.`
          })